server.port: ${APP_PORT:8085}
spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${DB_USER:root}
      password: ${DB_PASS:root}
      database: event
      port: ${DB_PORT:27017}
      host: ${DB_HOST:localhost}
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASS:admin}
  cloud:
    stream:
      function.definition: eventsLog
      default-binder: rabbit
      bindings:
        eventsLog-in-0:
          destination: event.type
        eventsLog-out-0:
          destination: event.type