server.port: ${APP_PORT:8085}
spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${DB_USER:root}
      password: ${DB_PASS:root}
      database: event
      port: ${DB_PORT:27017}
      host: ${DB_HOST:localhost}
